// ISO 4217 → ISO 3166-1 alpha-2 (или EU для евро)
// null — нет флага (металлы, корзины, спецкоды)
const CURRENCY_COUNTRY = {
  USD: 'US',
  EUR: 'EU',
  RUB: 'RU',
  TRY: 'TR',
  GBP: 'GB',
  JPY: 'JP',
  CNY: 'CN',
  CHF: 'CH',
  PLN: 'PL',
  CAD: 'CA',
  AUD: 'AU',
  UAH: 'UA',
  KZT: 'KZ',
  BYN: 'BY',
  SEK: 'SE',
  NOK: 'NO',
  DKK: 'DK',
  CZK: 'CZ',
  HUF: 'HU',
  RON: 'RO',
  BGN: 'BG',
  INR: 'IN',
  BRL: 'BR',
  MXN: 'MX',
  KRW: 'KR',
  SGD: 'SG',
  HKD: 'HK',
  NZD: 'NZ',
  ZAR: 'ZA',
  AED: 'AE',
  THB: 'TH',
  ILS: 'IL',
  AFN: 'AF',
  ALL: 'AL',
  AMD: 'AM',
  ANG: 'CW',
  AOA: 'AO',
  ARS: 'AR',
  AWG: 'AW',
  AZN: 'AZ',
  BAM: 'BA',
  BBD: 'BB',
  BDT: 'BD',
  BHD: 'BH',
  BIF: 'BI',
  BMD: 'BM',
  BND: 'BN',
  BOB: 'BO',
  BSD: 'BS',
  BTN: 'BT',
  BWP: 'BW',
  BZD: 'BZ',
  CDF: 'CD',
  CLP: 'CL',
  COP: 'CO',
  CRC: 'CR',
  CUP: 'CU',
  CVE: 'CV',
  DJF: 'DJ',
  DOP: 'DO',
  DZD: 'DZ',
  EGP: 'EG',
  ERN: 'ER',
  ETB: 'ET',
  FJD: 'FJ',
  FKP: 'FK',
  GEL: 'GE',
  GGP: 'GG',
  GHS: 'GH',
  GIP: 'GI',
  GMD: 'GM',
  GNF: 'GN',
  GTQ: 'GT',
  GYD: 'GY',
  HNL: 'HN',
  HRK: 'HR',
  HTG: 'HT',
  IDR: 'ID',
  IQD: 'IQ',
  IRR: 'IR',
  ISK: 'IS',
  JEP: 'JE',
  JMD: 'JM',
  JOD: 'JO',
  KES: 'KE',
  KGS: 'KG',
  KHR: 'KH',
  KMF: 'KM',
  KPW: 'KP',
  KWD: 'KW',
  KYD: 'KY',
  LAK: 'LA',
  LBP: 'LB',
  LKR: 'LK',
  LRD: 'LR',
  LSL: 'LS',
  LYD: 'LY',
  MAD: 'MA',
  MDL: 'MD',
  MGA: 'MG',
  MKD: 'MK',
  MMK: 'MM',
  MNT: 'MN',
  MOP: 'MO',
  MRU: 'MR',
  MUR: 'MU',
  MVR: 'MV',
  MWK: 'MW',
  MYR: 'MY',
  MZN: 'MZ',
  NAD: 'NA',
  NGN: 'NG',
  NIO: 'NI',
  NPR: 'NP',
  OMR: 'OM',
  PAB: 'PA',
  PEN: 'PE',
  PGK: 'PG',
  PHP: 'PH',
  PKR: 'PK',
  PYG: 'PY',
  QAR: 'QA',
  RSD: 'RS',
  RWF: 'RW',
  SAR: 'SA',
  SBD: 'SB',
  SCR: 'SC',
  SDG: 'SD',
  SHP: 'SH',
  SLE: 'SL',
  SLL: 'SL',
  SOS: 'SO',
  SRD: 'SR',
  SSP: 'SS',
  STN: 'ST',
  SYP: 'SY',
  SZL: 'SZ',
  TJS: 'TJ',
  TMT: 'TM',
  TND: 'TN',
  TOP: 'TO',
  TTD: 'TT',
  TWD: 'TW',
  TZS: 'TZ',
  UGX: 'UG',
  UYU: 'UY',
  UZS: 'UZ',
  VES: 'VE',
  VND: 'VN',
  VUV: 'VU',
  WST: 'WS',
  XAF: 'CM',
  XCD: 'AG',
  XOF: 'SN',
  XPF: 'PF',
  YER: 'YE',
  ZMW: 'ZM',
  ZWL: 'ZW',
  XAU: null,
  XAG: null,
  XPT: null,
  XPD: null,
  XDR: null,
};

// ISO 4217 → страна или null
export function currencyCountry(code) {
  const upper = String(code || '').toUpperCase();
  if (!upper) return null;
  if (Object.prototype.hasOwnProperty.call(CURRENCY_COUNTRY, upper)) {
    return CURRENCY_COUNTRY[upper];
  }
  // спецкоды IMF / металлы / тесты
  if (upper.startsWith('X')) return null;
  return null;
}

// alpha-2 → URL PNG-флага (flagcdn; на Windows emoji-флаги = буквы)
export function flagUrl(code) {
  const country = currencyCountry(code);
  if (!country || country.length !== 2) return '';
  return `https://flagcdn.com/w40/${country.toLowerCase()}.png`;
}

// разметка флага-картинки для списков; пустая строка если флага нет
export function flagMarkup(code) {
  const src = flagUrl(code);
  if (!src) return '';
  return `<span class="flag" aria-hidden="true"><img src="${src}" alt="" width="20" height="15" loading="lazy" decoding="async" onerror="this.closest('.flag')?.remove()" /></span>`;
}
